---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: zoa-runner-main-enterprise-contract
spec:
  application: rosa-hyperfleet-zoa
  contexts:
    - description: Component testing
      name: component
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/app-interface-standard
    - name: SINGLE_COMPONENT
      value: "true"
  resolverRef:
    params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
